# Generated by Django 5.1.13 on 2025-10-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_thumbnail_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
