"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-s-@56c%9*rv8zj7mjwp!l=gcc*iqjpu4z%yfkm7gf6-_w+-kzk'
)

def env_bool(name: str, default: bool = False) -> bool:
    val = os.getenv(name)
    if val is None:
        return default
    return val.lower() in {"1", "true", "yes", "on"}

# DEBUG controlled by DJANGO_DEBUG env ("1|true|yes|on" truthy)
DEBUG = env_bool("DJANGO_DEBUG", default=False)

# ALLOWED_HOSTS: comma separated in DJANGO_ALLOWED_HOSTS. When DEBUG true, include localhost conveniences.
_default_hosts = "localhost,127.0.0.1" if DEBUG else ""
ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", _default_hosts).split(",") if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    # Fallback safeguard for local dev so Django starts.
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# CSRF trusted origins (comma separated) DJANGO_CSRF_TRUSTED_ORIGINS
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "http://localhost:8080,http://localhost:5173"
).split(",") if o.strip()]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'portfolio',
    'projects',
    # Corrected app name (was project_minist typo -> mnist)
    'project_mnist',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Place CORS early so it can add headers before CommonMiddleware / CSRF.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]
# Allow overriding with comma separated origins.
_cors_extra = os.getenv("DJANGO_CORS_ALLOWED_ORIGINS")
if _cors_extra:
    CORS_ALLOWED_ORIGINS.extend([o.strip() for o in _cors_extra.split(",") if o.strip()])

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

_db_password = os.getenv("POSTGRES_PASSWORD")
if not _db_password:
    raise RuntimeError("POSTGRES_PASSWORD environment variable must be set for database connection.")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "myportfolio"),
        "USER": os.getenv("POSTGRES_USER", "myportfolio"),
        "PASSWORD": _db_password,
        "HOST": os.getenv("POSTGRES_HOST", "db"),
        "PORT": int(os.getenv("POSTGRES_PORT", "5432")),
        "CONN_MAX_AGE": 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = '/static'
MEDIA_URL = '/media/'
MEDIA_ROOT = '/media'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Security settings for production
# WARNING: Only enable SECURE_PROXY_SSL_HEADER if you are behind a trusted proxy.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
