# Generated by Django 5.1.13 on 2025-10-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Minseok Kim', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('profile_image', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile (Singleton)',
                'verbose_name_plural': 'Profile (Singleton)',
            },
        ),
    ]
